package com.example.mcgui.client.gui;

import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;

/**
 * Generated by Surface Studio from 'Sample Chest Screen'.
 *
 * Canvas: 176x166 GUI pixels.
 * Regenerating this file overwrites manual edits - subclass it instead.
 */
public class SampleChestScreen extends Screen {

    public static final int CANVAS_WIDTH = 176;
    public static final int CANVAS_HEIGHT = 166;

    /** Left edge of the layout once centred in the window. */
    private int originX;
    /** Top edge of the layout once centred in the window. */
    private int originY;

    public SampleChestScreen() {
        super(Component.translatable("gui.mcgui.sample_chest_screen.title"));
    }

    @Override
    protected void init() {
        this.originX = (this.width - CANVAS_WIDTH) / 2;
        this.originY = (this.height - CANVAS_HEIGHT) / 2;

        super.init();
    }

    @Override
    public void render(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) {
        this.renderBackground(graphics, mouseX, mouseY, partialTick);

        // Chest Background (panel.chest)
        graphics.fill(this.originX + 0, this.originY + 0, this.originX + 176, this.originY + 166, 0x80000000);
        // Title Bar (bar.header)
        graphics.drawString(this.font, "Custom Chest", this.originX + 8, this.originY + 6, 0xFFE0E0E0, true);
        // Chest Slot 0 (slot.inventory)
        graphics.fill(this.originX + 8, this.originY + 18, this.originX + 26, this.originY + 36, 0x80000000);
        // Chest Slot 1 (slot.inventory)
        graphics.fill(this.originX + 26, this.originY + 18, this.originX + 44, this.originY + 36, 0x80000000);
        // Chest Slot 2 (slot.inventory)
        graphics.fill(this.originX + 44, this.originY + 18, this.originX + 62, this.originY + 36, 0x80000000);
        // Chest Slot 3 (slot.inventory)
        graphics.fill(this.originX + 62, this.originY + 18, this.originX + 80, this.originY + 36, 0x80000000);
        // Chest Slot 4 (slot.inventory)
        graphics.fill(this.originX + 80, this.originY + 18, this.originX + 98, this.originY + 36, 0x80000000);
        // Chest Slot 5 (slot.inventory)
        graphics.fill(this.originX + 98, this.originY + 18, this.originX + 116, this.originY + 36, 0x80000000);
        // Chest Slot 6 (slot.inventory)
        graphics.fill(this.originX + 116, this.originY + 18, this.originX + 134, this.originY + 36, 0x80000000);
        // Chest Slot 7 (slot.inventory)
        graphics.fill(this.originX + 134, this.originY + 18, this.originX + 152, this.originY + 36, 0x80000000);
        // Chest Slot 8 (slot.inventory)
        graphics.fill(this.originX + 152, this.originY + 18, this.originX + 170, this.originY + 36, 0x80000000);
        // Chest Slot 9 (slot.inventory)
        graphics.fill(this.originX + 8, this.originY + 36, this.originX + 26, this.originY + 54, 0x80000000);
        // Chest Slot 10 (slot.inventory)
        graphics.fill(this.originX + 26, this.originY + 36, this.originX + 44, this.originY + 54, 0x80000000);
        // Chest Slot 11 (slot.inventory)
        graphics.fill(this.originX + 44, this.originY + 36, this.originX + 62, this.originY + 54, 0x80000000);
        // Chest Slot 12 (slot.inventory)
        graphics.fill(this.originX + 62, this.originY + 36, this.originX + 80, this.originY + 54, 0x80000000);
        // Chest Slot 13 (slot.inventory)
        graphics.fill(this.originX + 80, this.originY + 36, this.originX + 98, this.originY + 54, 0x80000000);
        // Chest Slot 14 (slot.inventory)
        graphics.fill(this.originX + 98, this.originY + 36, this.originX + 116, this.originY + 54, 0x80000000);
        // Chest Slot 15 (slot.inventory)
        graphics.fill(this.originX + 116, this.originY + 36, this.originX + 134, this.originY + 54, 0x80000000);
        // Chest Slot 16 (slot.inventory)
        graphics.fill(this.originX + 134, this.originY + 36, this.originX + 152, this.originY + 54, 0x80000000);
        // Chest Slot 17 (slot.inventory)
        graphics.fill(this.originX + 152, this.originY + 36, this.originX + 170, this.originY + 54, 0x80000000);
        // Chest Slot 18 (slot.inventory)
        graphics.fill(this.originX + 8, this.originY + 54, this.originX + 26, this.originY + 72, 0x80000000);
        // Chest Slot 19 (slot.inventory)
        graphics.fill(this.originX + 26, this.originY + 54, this.originX + 44, this.originY + 72, 0x80000000);
        // Chest Slot 20 (slot.inventory)
        graphics.fill(this.originX + 44, this.originY + 54, this.originX + 62, this.originY + 72, 0x80000000);
        // Chest Slot 21 (slot.inventory)
        graphics.fill(this.originX + 62, this.originY + 54, this.originX + 80, this.originY + 72, 0x80000000);
        // Chest Slot 22 (slot.inventory)
        graphics.fill(this.originX + 80, this.originY + 54, this.originX + 98, this.originY + 72, 0x80000000);
        // Chest Slot 23 (slot.inventory)
        graphics.fill(this.originX + 98, this.originY + 54, this.originX + 116, this.originY + 72, 0x80000000);
        // Chest Slot 24 (slot.inventory)
        graphics.fill(this.originX + 116, this.originY + 54, this.originX + 134, this.originY + 72, 0x80000000);
        // Chest Slot 25 (slot.inventory)
        graphics.fill(this.originX + 134, this.originY + 54, this.originX + 152, this.originY + 72, 0x80000000);
        // Chest Slot 26 (slot.inventory)
        graphics.fill(this.originX + 152, this.originY + 54, this.originX + 170, this.originY + 72, 0x80000000);
        // Inventory Slot 27 (slot.inventory)
        graphics.fill(this.originX + 8, this.originY + 84, this.originX + 26, this.originY + 102, 0x80000000);
        // Inventory Slot 28 (slot.inventory)
        graphics.fill(this.originX + 26, this.originY + 84, this.originX + 44, this.originY + 102, 0x80000000);
        // Inventory Slot 29 (slot.inventory)
        graphics.fill(this.originX + 44, this.originY + 84, this.originX + 62, this.originY + 102, 0x80000000);
        // Inventory Slot 30 (slot.inventory)
        graphics.fill(this.originX + 62, this.originY + 84, this.originX + 80, this.originY + 102, 0x80000000);
        // Inventory Slot 31 (slot.inventory)
        graphics.fill(this.originX + 80, this.originY + 84, this.originX + 98, this.originY + 102, 0x80000000);
        // Inventory Slot 32 (slot.inventory)
        graphics.fill(this.originX + 98, this.originY + 84, this.originX + 116, this.originY + 102, 0x80000000);
        // Inventory Slot 33 (slot.inventory)
        graphics.fill(this.originX + 116, this.originY + 84, this.originX + 134, this.originY + 102, 0x80000000);
        // Inventory Slot 34 (slot.inventory)
        graphics.fill(this.originX + 134, this.originY + 84, this.originX + 152, this.originY + 102, 0x80000000);
        // Inventory Slot 35 (slot.inventory)
        graphics.fill(this.originX + 152, this.originY + 84, this.originX + 170, this.originY + 102, 0x80000000);
        // Inventory Slot 36 (slot.inventory)
        graphics.fill(this.originX + 8, this.originY + 102, this.originX + 26, this.originY + 120, 0x80000000);
        // Inventory Slot 37 (slot.inventory)
        graphics.fill(this.originX + 26, this.originY + 102, this.originX + 44, this.originY + 120, 0x80000000);
        // Inventory Slot 38 (slot.inventory)
        graphics.fill(this.originX + 44, this.originY + 102, this.originX + 62, this.originY + 120, 0x80000000);
        // Inventory Slot 39 (slot.inventory)
        graphics.fill(this.originX + 62, this.originY + 102, this.originX + 80, this.originY + 120, 0x80000000);
        // Inventory Slot 40 (slot.inventory)
        graphics.fill(this.originX + 80, this.originY + 102, this.originX + 98, this.originY + 120, 0x80000000);
        // Inventory Slot 41 (slot.inventory)
        graphics.fill(this.originX + 98, this.originY + 102, this.originX + 116, this.originY + 120, 0x80000000);
        // Inventory Slot 42 (slot.inventory)
        graphics.fill(this.originX + 116, this.originY + 102, this.originX + 134, this.originY + 120, 0x80000000);
        // Inventory Slot 43 (slot.inventory)
        graphics.fill(this.originX + 134, this.originY + 102, this.originX + 152, this.originY + 120, 0x80000000);
        // Inventory Slot 44 (slot.inventory)
        graphics.fill(this.originX + 152, this.originY + 102, this.originX + 170, this.originY + 120, 0x80000000);
        // Inventory Slot 45 (slot.inventory)
        graphics.fill(this.originX + 8, this.originY + 120, this.originX + 26, this.originY + 138, 0x80000000);
        // Inventory Slot 46 (slot.inventory)
        graphics.fill(this.originX + 26, this.originY + 120, this.originX + 44, this.originY + 138, 0x80000000);
        // Inventory Slot 47 (slot.inventory)
        graphics.fill(this.originX + 44, this.originY + 120, this.originX + 62, this.originY + 138, 0x80000000);
        // Inventory Slot 48 (slot.inventory)
        graphics.fill(this.originX + 62, this.originY + 120, this.originX + 80, this.originY + 138, 0x80000000);
        // Inventory Slot 49 (slot.inventory)
        graphics.fill(this.originX + 80, this.originY + 120, this.originX + 98, this.originY + 138, 0x80000000);
        // Inventory Slot 50 (slot.inventory)
        graphics.fill(this.originX + 98, this.originY + 120, this.originX + 116, this.originY + 138, 0x80000000);
        // Inventory Slot 51 (slot.inventory)
        graphics.fill(this.originX + 116, this.originY + 120, this.originX + 134, this.originY + 138, 0x80000000);
        // Inventory Slot 52 (slot.inventory)
        graphics.fill(this.originX + 134, this.originY + 120, this.originX + 152, this.originY + 138, 0x80000000);
        // Inventory Slot 53 (slot.inventory)
        graphics.fill(this.originX + 152, this.originY + 120, this.originX + 170, this.originY + 138, 0x80000000);
        // Hotbar Slot 54 (slot.inventory)
        graphics.fill(this.originX + 8, this.originY + 142, this.originX + 26, this.originY + 160, 0x80000000);
        // Hotbar Slot 55 (slot.inventory)
        graphics.fill(this.originX + 26, this.originY + 142, this.originX + 44, this.originY + 160, 0x80000000);
        // Hotbar Slot 56 (slot.inventory)
        graphics.fill(this.originX + 44, this.originY + 142, this.originX + 62, this.originY + 160, 0x80000000);
        // Hotbar Slot 57 (slot.inventory)
        graphics.fill(this.originX + 62, this.originY + 142, this.originX + 80, this.originY + 160, 0x80000000);
        // Hotbar Slot 58 (slot.inventory)
        graphics.fill(this.originX + 80, this.originY + 142, this.originX + 98, this.originY + 160, 0x80000000);
        // Hotbar Slot 59 (slot.inventory)
        graphics.fill(this.originX + 98, this.originY + 142, this.originX + 116, this.originY + 160, 0x80000000);
        // Hotbar Slot 60 (slot.inventory)
        graphics.fill(this.originX + 116, this.originY + 142, this.originX + 134, this.originY + 160, 0x80000000);
        // Hotbar Slot 61 (slot.inventory)
        graphics.fill(this.originX + 134, this.originY + 142, this.originX + 152, this.originY + 160, 0x80000000);
        // Hotbar Slot 62 (slot.inventory)
        graphics.fill(this.originX + 152, this.originY + 142, this.originX + 170, this.originY + 160, 0x80000000);

        super.render(graphics, mouseX, mouseY, partialTick);
    }

    @Override
    public boolean isPauseScreen() {
        return false;
    }
}
