package com.mcguidesigner.exporters.tools

import com.mcguidesigner.core.serialization.ProjectSerializer
import com.mcguidesigner.core.templates.BuiltInTemplates
import com.mcguidesigner.core.validation.ProjectValidator
import com.mcguidesigner.core.validation.Severity
import com.mcguidesigner.exporters.ExportManager
import com.mcguidesigner.exporters.bytes
import java.io.File
import kotlin.system.exitProcess

/**
 * Regenerates `/templates` and `/templates/sample-output` from the built-in
 * template definitions, then validates every one of them.
 *
 * Run through Gradle: `./gradlew exportTemplates`
 *
 * Keeping the committed `.mcgui` files generated rather than hand-written
 * means they can never drift away from the element catalog - if a property is
 * renamed, this task regenerates them and CI's `validateProjects` fails loudly
 * if anything no longer checks out.
 */
fun main(args: Array<String>) {
    val repositoryRoot = File(args.firstOrNull() ?: ".").absoluteFile
    val templatesDir = File(repositoryRoot, "templates")
    val sampleDir = File(templatesDir, "sample-output")

    templatesDir.mkdirs()
    if (sampleDir.exists()) sampleDir.deleteRecursively()
    sampleDir.mkdirs()

    var errors = 0
    val index = StringBuilder()
    index.appendLine("# Bundled templates")
    index.appendLine()
    index.appendLine("Generated by `./gradlew exportTemplates`. Do not edit by hand.")
    index.appendLine()
    index.appendLine("| File | Template | Edition | Form | Canvas | Elements |")
    index.appendLine("| --- | --- | --- | --- | --- | --- |")

    BuiltInTemplates.all.forEach { template ->
        val project = template.canonical()
        val file = File(templatesDir, "${template.id}.mcgui")
        file.writeText(ProjectSerializer.encode(project))

        val report = ProjectValidator.validate(project, strict = true)
        val blocking = report.issues.filter { it.severity == Severity.ERROR }
        if (blocking.isNotEmpty()) {
            errors += blocking.size
            System.err.println("[FAIL] ${template.id}")
            blocking.forEach { System.err.println("       ${it.code}: ${it.message}") }
        } else {
            println(
                "[ok]   ${file.name}  (${project.allElements.size} elements, " +
                    "${report.warningCount} warnings)",
            )
        }

        index.appendLine(
            "| `${file.name}` | ${template.title} | ${template.edition.displayName} | " +
                "${template.form.displayName} | ${project.canvas.width}x${project.canvas.height} | " +
                "${project.allElements.size} |",
        )
    }

    // One fully worked example of every export the app can produce, so the
    // repository documents the output formats without anyone having to run
    // the GUI first.
    val demo = BuiltInTemplates.demo.canonical("Sample Chest Screen")
    ExportManager.exportAll(demo).forEach { bundle ->
        val targetDir = File(sampleDir, bundle.target.id)
        bundle.files.forEach { exportFile ->
            val destination = File(targetDir, exportFile.path)
            destination.parentFile.mkdirs()
            destination.writeBytes(exportFile.bytes())
        }
        println("[ok]   sample-output/${bundle.target.id}  (${bundle.files.size} files)")
    }

    File(sampleDir, "README.md").writeText(
        """
        # Sample export output

        Generated by `./gradlew exportTemplates` from the **${demo.name}** template.

        | Folder | What it is |
        | --- | --- |
        | `java-pack/` | A Java Edition resource pack plus a generated `Screen` subclass. |
        | `bedrock-pack/` | A Bedrock Edition resource pack with real JSON UI. |
        | `project-json/` | The `.mcgui` document itself. |
        | `code/` | The design converted to a standalone HTML + CSS page. |

        Everything here is regenerated from scratch on each run - edit the
        template in `sharedCore` rather than these files.
        """.trimIndent(),
    )

    File(templatesDir, "README.md").writeText(index.toString())

    if (errors > 0) {
        System.err.println("$errors validation error(s) in bundled templates.")
        exitProcess(1)
    }
    println("Wrote ${BuiltInTemplates.all.size} templates and 4 sample export bundles.")
}
